name: Build

on:
  push:
    branches:
     - '*'
  pull_request:
    branches:
     - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: pnpm
    - run: pnpm install
    - run: pnpm build
    - uses: actions/upload-artifact@v4
      with:
        path: dist/
